### PR TITLE
feat(scss): added support for scss

### LINKED ISSUE #18: Adding support for new languages
Add support for new languages in Nirjas. Some commonly used languages (or file type) whose support can be added
- [x] Typescript (.ts) https://github.com/fossology/Nirjas/pull/19
- [x] Dart (.dart) https://github.com/fossology/Nirjas/pull/24
- [ ] Scss  (.scss)
- [x] React js (.jsx) https://github.com/fossology/Nirjas/pull/21
- [x] Tsx (.tsx) https://github.com/fossology/Nirjas/pull/23
I would like to work on it. Being a first time contributor to fossology, it would be helpful if you could guide me

### PR DESCRIPTION
**Pull request by Aman-Codes**
# Description 
Added support for scss

Closes #18

### CODE REVIEW

**Comment by GMishx** [comment]
I just tested the branch with the test code (`_reboot.scss`) and it seems to be missing all comments single line comments (starting with `//`) which are continuing for more than 2 lines. Any idea what that is happening?

**Comment by Aman-Codes** [comment]
> I just tested the branch with the test code (`_reboot.scss`) and it seems to be missing all comments single line comments (starting with `//`) which are continuing for more than 2 lines. Any idea what that is happening?

I gone through the code and found that it is due to the regex `([^\/]\/\/[^\/]\s*[\w #\.()@+-_*\d]*)` present [here](https://github.com/Aman-Codes/Nirjas/blob/scss_branch/nirjas/binder.py#L164) which I added to separate normal comments from documentation comments (otherwise extracted documentation comments will have an `/` in the beginning)
This regex is assuming that their **should be a character** before `//`  which should not be `/`. 
I tried checking and testing many other regex pattern [here](https://regexr.com/) but in vain
Is there any way by which I can improve the regex pattern or is it fine to have an extra `/` in front of documentation comment

**Comment by GMishx** [comment]
Well in that case, you can try adding a `?` to it like `([^\/]?\/\/[^\/]\s*[\w #\.()@+-_*\d]*)`

**Comment by Aman-Codes** [comment]
> Well in that case, you can try adding a `?` to it like `([^\/]?\/\/[^\/]?\s*[\w #\.()@+-_*\d]*)`

I tried that but it is same as checking for `(\/\/\s*[\w #\.()@+-_*\d]*)` as it also includes /// comment in it and will lead to overcounting of comments

**Comment by GMishx** [comment]
Aha, then how about `((?<!\/)\/\/(?!\/)\s*[\w #\.()@+-_*\d]*)` ?

**Comment by Aman-Codes** [comment]
> Aha, then how about `((?<!\/)\/\/(?!\/)\s*[\w #\.()@+-_*\d]*)` ?

Yeah this seems to be a perfect one. Thanks

**Comment by Aman-Codes** [comment]
Also in this line [here](https://github.com/fossology/Nirjas/blob/master/nirjas/binder.py#L38) was it assumed that the comment sign will be of single character as I updated it

**Pull request merged**
