### PR TITLE
Flake8 Linter added

### LINKED ISSUE #39: Code Formatting and Linting is required.
Currently, Nirjas codebase is not following any specific Linters and formatters. Having a linter is useful for uniformity in coding style.

### What to do?
- [ ] Either Flake8 or Pylint can be introduced as a linter.
- [ ] Separate code linting stage can be introduced in CI pipeline.

### PR DESCRIPTION
**Pull request by soham4abc**
Fixes #39

Flake8 Linter added. Please Do have a look

### CODE REVIEW

**Comment by soham4abc** [comment]
Would you like to follow the black code formatting style or flake8 is all you need? @Kaushl2208

**Comment by soham4abc** [comment]
All lint errors fixed please do have a look!

**Comment by Kaushl2208** [comment]
Hey @soham4abc , Thanks for your efforts! I see that you have ignored (W503,E203) in the linters. These are checks that we require. 
So, Please remove that!

**Comment by soham4abc** [comment]
> Hey @soham4abc , Thanks for your efforts! I see that you have ignored (W503,E203) in the linters. These are checks that we require. So, Please remove that!

Sure!

**Comment by soham4abc** [comment]
I pushed the requested changes Please do have a look @GMishx

**Review by Kaushl2208 — APPROVED** [review]
Hey @soham4abc , Changes looks good now. Ready to merge.
Thankyou for your contributions.

**Comment by soham4abc** [comment]
> Hey @soham4abc , Changes looks good now. Ready to merge. Thankyou for your contributions.

Happy to help!

**Pull request merged**
