### PR TITLE
feat(julia): Add julia language support

### PR DESCRIPTION
**Pull request by aman1971**
pull request for #34

### CODE REVIEW

**Comment by GMishx** [comment]
Hello @aman1971 . Thank you for your contribution but we have recently merged a PR for Julia #52 

Since your changes are also interesting and compliment changes in #52, can you please rebase your changes on top of it and push?

**Comment by aman1971** [comment]
Okay sir

**Review by GMishx — APPROVED** [review]
Changes looks good. Need test.

**Comment by GMishx** [comment]
@aman1971 can you please squash your commits into one so we can go head with merging your branch?

**Comment by GMishx** [comment]
Looks like linter is failing @aman1971 

```
./nirjas/binder.py:326:61: W292 no newline at end of file
./nirjas/languages/tests/test_julia.py:153:1: W293 blank line contains whitespace
Error: Process completed with exit code 1.
```

Please fix the issue and amend in the same commit.

**Comment by aman1971** [comment]
okay @GMishx

**Pull request merged**
